-- Create Tables

-- Create the Products table
CREATE TABLE Products (
    ProductId VARCHAR(10) PRIMARY KEY,
    ProductType VARCHAR(50),
    URL VARCHAR(1000)
);

-- Create the Users table
CREATE TABLE Users (
    UserId VARCHAR(50) PRIMARY KEY
);

-- Create the Rating table (connecting the Products and Users)
CREATE TABLE Ratings (
    RatingId NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    Rating NUMBER,
    Timestamp NUMBER,
    ProductId VARCHAR(10),
    UserId VARCHAR(50),
    FOREIGN KEY (ProductId) REFERENCES Products(ProductId),
    FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

